In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('assets/data.csv')

In [4]:
df.head()

        date  subscribers  reviews
0  2019/1/17         2671      194
1  2019/1/18         2671      195
2  2019/1/19         2674      197
3  2019/1/20         2685      199
4  2019/1/21         2695      199

In [9]:
type(df['date'][0])

str

In [10]:
df['date'][0]

'2019/1/17'

In [11]:
import datetime

In [13]:
datetime.datetime.strptime(df['date'][0],'%Y/%m/%d').date()

datetime.date(2019, 1, 17)

In [15]:
dates = []
for _date in df['date']:
    date = datetime.datetime.strptime(_date,'%Y/%m/%d').date()
    dates.append(date)

In [17]:
# dates

In [21]:
#受講生の数
n_subscribers = df['subscribers'].values
n_subscribers

array([ 2671,  2671,  2674,  2685,  2695,  2701,  2710,  2718,  2722,
        2725,  2734,  2753,  2773,  2785,  2803,  2845,  2847,  2847,
        2851,  2852,  2857,  2861,  2865,  2870,  2875,  2892,  2906,
        2919,  2942,  2974,  2977,  2978,  2981,  2983,  2984,  2987,
        2989,  2993,  2995,  3009,  3014,  3023,  3031,  3052,  3060,
        3062,  3063,  3066,  3071,  3074,  3076,  3077,  3080,  3087,
        3089,  3093,  3098,  3104,  3112,  3120,  3131,  3142,  3162,
        3173,  3180,  3187,  3189,  3196,  3212,  3220,  3226,  3241,
        3253,  3255,  3258,  3262,  3264,  3272,  3275,  3276,  3279,
        3285,  3300,  3306,  3312,  3319,  3324,  3325,  3329,  3331,
        3332,  3333,  3336,  3339,  3343,  3349,  3357,  3370,  3388,
        3412,  3437,  3439,  3440,  3447,  3466,  3481,  3504,  3522,
        3527,  3533,  3543,  3546,  3555,  3566,  3583,  3594,  3614,
        3633,  3647,  3648,  3649,  3651,  3654,  3658,  3671,  3675,
        3681,  3694,  3699,  3711,  3722,  3734,  3766,  3781,  3784,
        3789,  3790,  3793,  3795,  3808,  3830,  3843,  3857,  3870,
        3895,  3919,  3942,  3983,  4022,  4053,  4058,  4063,  4064,
        4065,  4066,  4069,  4070,  4073,  4084,  4108,  4122,  4132,
        4150,  4162,  4164,  4167,  4174,  4179,  4187,  4200,  4210,
        4211,  4214,  4219,  4223,  4228,  4236,  4239,  4243,  4250,
        4265,  4288,  4313,  4329,  4329,  4329,  4333,  4335,  4353,
        4370,  4397,  4419,  4422,  4423,  4425,  4427,  4432,  4433,
        4435,  4437,  4440,  4444,  4452,  4466,  4493,  4521,  4528,
        4529,  4532,  4534,  4535,  4539,  4539,  4541,  4545,  4545,
        4561,  4590,  4624,  4641,  4665,  4702,  4730,  4761,  4793,
        4846,  4878,  4884,  4888,  4887,  4888,  4890,  4892,  4894,
        4896,  4907,  4918,  4935,  4949,  4965,  4966,  4966,  4970,
        4972,  4974,  4996,  4998,  5001,  5004,  5005,  5012,  5023,
        5033,  5068,  5084,  5088,  5097,  5113,  5117,  5120,  5128,
        5133,  5137,  5144,  5160,  5166,  5167,  5168,  5169,  5170,
        5170,  5179,  5185,  5187,  5189,  5191,  5193,  5194,  5197,
        5210,  5223,  5232,  5233,  5234,  5236,  5240,  5242,  5243,
        5244,  5246,  5246,  5247,  5269,  5284,  5298,  5307,  5313,
        5314,  5314,  5316,  5326,  5337,  5338,  5342,  5343,  5347,
        5348,  5351,  5356,  5383,  5409,  5435,  5450,  5479,  5503,
        5554,  5643,  5652,  5654,  5678,  5706,  5747,  5802,  5807,
        5811,  5811,  5813,  5819,  5825,  5830,  5833,  5837,  5839,
        5840,  5846,  5847,  5849,  5850,  5852,  5870,  5878,  5888,
        5906,  5927,  5930,  5933,  5936,  5937,  5964,  5989,  5999,
        6011,  6023,  6042,  6060,  6089,  6121,  6174,  6178,  6182,
        6188,  6191,  6193,  6196,  6201,  6200,  6204,  6206,  6212,
        6213,  6215,  6219,  6222,  6223,  6224,  6229,  6248,  6281,
        6286,  6291,  6294,  6299,  6310,  6319,  6337,  6352,  6353,
        6356,  6359,  6361,  6366,  6370,  6387,  6399,  6399,  6407,
        6411,  6412,  6413,  6428,  6436,  6439,  6442,  6455,  6460,
        6470,  6482,  6495,  6500,  6504,  6510,  6519,  6527,  6534,
        6539,  6549,  6568,  6590,  6609,  6636,  6640,  6645,  6649,
        6652,  6672,  6687,  6707,  6729,  6764,  6771,  6776,  6783,
        6785,  6790,  6792,  6798,  6805,  6809,  6832,  6867,  6868,
        6877,  6882,  6886,  6892,  6912,  6913,  6921,  6927,  6938,
        6941,  6941,  6941,  6941,  6941,  6948,  6956,  6982,  7003,
        7024,  7050,  7092,  7154,  7233,  7245,  7257,  7265,  7269,
        7276,  7281,  7290,  7298,  7353,  7404,  7411,  7423,  7429,
        7439,  7487,  7516,  7532,  7557,  7593,  7634,  7664,  7702,
        7758,  7823,  7826,  7827,  7831,  7841,  7842,  7845,  7854,
        7861,  7870,  7876,  7884,  7928,  7961,  7969,  7978,  7979,
        7979,  7999,  8018,  8040,  8069,  8075,  8080,  8083,  8096,
        8104,  8109,  8116,  8143,  8169,  8196,  8201,  8206,  8212,
        8217,  8222,  8230,  8234,  8241,  8246,  8255,  8279,  8304,
        8308,  8312,  8318,  8325,  8340,  8347,  8358,  8368,  8376,
        8392,  8414,  8437,  8468,  8473,  8475,  8482,  8485,  8500,
        8517,  8536,  8539,  8540,  8545,  8551,  8553,  8556,  8564,
        8572,  8574,  8583,  8601,  8614,  8625,  8642,  8657,  8662,
        8665,  8669,  8671,  8680,  8690,  8694,  8696,  8697,  8704,
        8705,  8707,  8710,  8714,  8723,  8725,  8731,  8749,  8767,
        8784,  8793,  8808,  8825,  8835,  8857,  8883,  8916,  8922,
        8925,  8928,  8932,  8939,  8940,  8956,  8966,  8972,  8978,
        8986,  8989,  8991,  8995,  9000,  9002,  9022,  9030,  9030,
        9030,  9030,  9030,  9044,  9059,  9062,  9063,  9065,  9066,
        9068,  9073,  9076,  9079,  9085,  9089,  9100,  9111,  9127,
        9140,  9142,  9151,  9156,  9170,  9190,  9194,  9197,  9200,
        9204,  9214,  9220,  9248,  9265,  9297,  9300,  9308,  9314,
        9322,  9335,  9353,  9362,  9363,  9371,  9378,  9395,  9417,
        9437,  9457,  9462,  9465,  9465,  9469,  9476,  9481,  9484,
        9491,  9493,  9497,  9501,  9507,  9544,  9551,  9556,  9563,
        9565,  9569,  9581,  9583,  9585,  9611,  9647,  9681,  9708,
        9733,  9769,  9838,  9926,  9931,  9935,  9970,  9987, 10005,
       10031, 10061, 10110, 10112, 10116, 10118, 10123, 10138, 10155,
       10185, 10196, 10202, 10205, 10215, 10230, 10235])

In [26]:
#レビューの数
n_reviews = df['reviews'].values
n_reviews

array([ 194,  195,  197,  199,  199,  200,  200,  201,  201,  201,  202,
        204,  206,  208,  210,  211,  213,  213,  217,  218,  219,  220,
        222,  224,  224,  227,  229,  229,  231,  232,  234,  234,  234,
        234,  237,  239,  239,  241,  241,  241,  243,  243,  243,  244,
        245,  246,  249,  252,  254,  255,  256,  258,  258,  261,  261,
        262,  262,  262,  262,  262,  265,  266,  266,  268,  269,  271,
        271,  274,  274,  274,  275,  275,  278,  278,  280,  282,  282,
        282,  284,  287,  289,  289,  291,  293,  295,  295,  295,  297,
        298,  299,  299,  299,  299,  299,  300,  302,  303,  303,  304,
        304,  305,  305,  308,  309,  310,  311,  314,  317,  322,  324,
        327,  328,  330,  332,  334,  335,  338,  340,  344,  349,  349,
        351,  351,  354,  354,  359,  359,  361,  361,  364,  368,  373,
        374,  375,  375,  378,  379,  380,  383,  385,  386,  387,  390,
        394,  395,  397,  399,  402,  404,  409,  410,  414,  417,  422,
        424,  425,  426,  427,  427,  427,  433,  436,  440,  440,  446,
        448,  450,  455,  456,  456,  458,  458,  464,  464,  468,  469,
        469,  471,  471,  473,  476,  476,  483,  483,  486,  487,  492,
        493,  494,  496,  500,  504,  507,  513,  516,  518,  519,  520,
        522,  522,  526,  528,  528,  529,  529,  530,  531,  533,  534,
        537,  537,  539,  540,  541,  544,  545,  548,  549,  549,  552,
        554,  557,  561,  564,  566,  566,  571,  572,  573,  574,  575,
        577,  577,  578,  578,  579,  581,  583,  583,  584,  587,  587,
        590,  590,  592,  596,  601,  601,  603,  605,  605,  609,  609,
        612,  613,  614,  615,  617,  618,  620,  622,  624,  628,  630,
        633,  637,  639,  641,  644,  646,  649,  651,  651,  652,  653,
        654,  655,  656,  658,  659,  663,  663,  664,  665,  666,  670,
        671,  671,  674,  674,  676,  676,  679,  681,  683,  684,  687,
        687,  688,  689,  691,  691,  692,  692,  695,  697,  697,  700,
        700,  700,  704,  709,  714,  714,  715,  716,  718,  720,  723,
        723,  723,  726,  728,  728,  732,  732,  735,  735,  737,  739,
        739,  740,  742,  744,  745,  745,  746,  746,  746,  747,  748,
        748,  749,  749,  749,  750,  752,  753,  760,  764,  768,  768,
        771,  772,  776,  778,  780,  781,  782,  784,  784,  788,  792,
        793,  793,  795,  797,  801,  803,  806,  808,  808,  811,  811,
        811,  812,  812,  813,  816,  820,  820,  820,  821,  824,  827,
        829,  833,  834,  836,  843,  845,  848,  852,  854,  854,  857,
        860,  861,  861,  862,  862,  867,  868,  869,  871,  872,  873,
        876,  876,  878,  885,  890,  893,  894,  894,  897,  897,  902,
        906,  909,  909,  911,  916,  920,  922,  926,  928,  933,  934,
        939,  943,  948,  950,  951,  952,  953,  957,  958,  963,  968,
        974,  977,  979,  979,  982,  987,  991,  993,  995,  996,  998,
        998,  998,  998,  998, 1002, 1006, 1007, 1007, 1012, 1016, 1017,
       1021, 1028, 1031, 1033, 1045, 1048, 1053, 1055, 1059, 1063, 1064,
       1069, 1073, 1076, 1080, 1088, 1094, 1105, 1113, 1120, 1126, 1129,
       1147, 1154, 1156, 1161, 1167, 1172, 1179, 1180, 1187, 1189, 1191,
       1195, 1200, 1205, 1208, 1212, 1214, 1216, 1219, 1220, 1222, 1226,
       1229, 1229, 1238, 1240, 1241, 1246, 1250, 1255, 1260, 1264, 1265,
       1269, 1276, 1280, 1283, 1284, 1286, 1289, 1291, 1295, 1298, 1301,
       1305, 1306, 1308, 1311, 1312, 1317, 1320, 1323, 1323, 1330, 1331,
       1334, 1336, 1339, 1340, 1342, 1344, 1348, 1350, 1354, 1358, 1358,
       1359, 1359, 1363, 1363, 1365, 1369, 1371, 1374, 1376, 1382, 1386,
       1389, 1391, 1393, 1394, 1394, 1396, 1399, 1402, 1403, 1403, 1403,
       1404, 1405, 1408, 1409, 1411, 1416, 1420, 1420, 1420, 1421, 1421,
       1424, 1424, 1426, 1426, 1426, 1429, 1439, 1443, 1444, 1445, 1447,
       1450, 1451, 1457, 1459, 1460, 1460, 1460, 1461, 1465, 1467, 1470,
       1471, 1473, 1474, 1476, 1477, 1478, 1478, 1478, 1478, 1478, 1481,
       1484, 1486, 1489, 1492, 1494, 1495, 1495, 1495, 1499, 1501, 1501,
       1502, 1505, 1507, 1515, 1516, 1517, 1518, 1519, 1521, 1522, 1526,
       1526, 1528, 1531, 1536, 1540, 1540, 1542, 1546, 1547, 1549, 1552,
       1554, 1556, 1560, 1563, 1563, 1565, 1566, 1567, 1569, 1571, 1575,
       1576, 1578, 1578, 1579, 1581, 1587, 1589, 1592, 1593, 1594, 1595,
       1597, 1599, 1603, 1605, 1606, 1608, 1613, 1613, 1614, 1618, 1618,
       1618, 1618, 1618, 1618, 1618, 1618, 1618, 1618, 1618, 1641, 1658,
       1662, 1663, 1679, 1683, 1686, 1687, 1690, 1693, 1694, 1695, 1698,
       1702, 1703, 1708, 1709, 1710])

In [28]:
diff_subscribers = df['subscribers'].diff().values
diff_subscribers

array([nan,  0.,  3., 11., 10.,  6.,  9.,  8.,  4.,  3.,  9., 19., 20.,
       12., 18., 42.,  2.,  0.,  4.,  1.,  5.,  4.,  4.,  5.,  5., 17.,
       14., 13., 23., 32.,  3.,  1.,  3.,  2.,  1.,  3.,  2.,  4.,  2.,
       14.,  5.,  9.,  8., 21.,  8.,  2.,  1.,  3.,  5.,  3.,  2.,  1.,
        3.,  7.,  2.,  4.,  5.,  6.,  8.,  8., 11., 11., 20., 11.,  7.,
        7.,  2.,  7., 16.,  8.,  6., 15., 12.,  2.,  3.,  4.,  2.,  8.,
        3.,  1.,  3.,  6., 15.,  6.,  6.,  7.,  5.,  1.,  4.,  2.,  1.,
        1.,  3.,  3.,  4.,  6.,  8., 13., 18., 24., 25.,  2.,  1.,  7.,
       19., 15., 23., 18.,  5.,  6., 10.,  3.,  9., 11., 17., 11., 20.,
       19., 14.,  1.,  1.,  2.,  3.,  4., 13.,  4.,  6., 13.,  5., 12.,
       11., 12., 32., 15.,  3.,  5.,  1.,  3.,  2., 13., 22., 13., 14.,
       13., 25., 24., 23., 41., 39., 31.,  5.,  5.,  1.,  1.,  1.,  3.,
        1.,  3., 11., 24., 14., 10., 18., 12.,  2.,  3.,  7.,  5.,  8.,
       13., 10.,  1.,  3.,  5.,  4.,  5.,  8.,  3.,  4.,  7., 15., 23.,
       25., 16.,  0.,  0.,  4.,  2., 18., 17., 27., 22.,  3.,  1.,  2.,
        2.,  5.,  1.,  2.,  2.,  3.,  4.,  8., 14., 27., 28.,  7.,  1.,
        3.,  2.,  1.,  4.,  0.,  2.,  4.,  0., 16., 29., 34., 17., 24.,
       37., 28., 31., 32., 53., 32.,  6.,  4., -1.,  1.,  2.,  2.,  2.,
        2., 11., 11., 17., 14., 16.,  1.,  0.,  4.,  2.,  2., 22.,  2.,
        3.,  3.,  1.,  7., 11., 10., 35., 16.,  4.,  9., 16.,  4.,  3.,
        8.,  5.,  4.,  7., 16.,  6.,  1.,  1.,  1.,  1.,  0.,  9.,  6.,
        2.,  2.,  2.,  2.,  1.,  3., 13., 13.,  9.,  1.,  1.,  2.,  4.,
        2.,  1.,  1.,  2.,  0.,  1., 22., 15., 14.,  9.,  6.,  1.,  0.,
        2., 10., 11.,  1.,  4.,  1.,  4.,  1.,  3.,  5., 27., 26., 26.,
       15., 29., 24., 51., 89.,  9.,  2., 24., 28., 41., 55.,  5.,  4.,
        0.,  2.,  6.,  6.,  5.,  3.,  4.,  2.,  1.,  6.,  1.,  2.,  1.,
        2., 18.,  8., 10., 18., 21.,  3.,  3.,  3.,  1., 27., 25., 10.,
       12., 12., 19., 18., 29., 32., 53.,  4.,  4.,  6.,  3.,  2.,  3.,
        5., -1.,  4.,  2.,  6.,  1.,  2.,  4.,  3.,  1.,  1.,  5., 19.,
       33.,  5.,  5.,  3.,  5., 11.,  9., 18., 15.,  1.,  3.,  3.,  2.,
        5.,  4., 17., 12.,  0.,  8.,  4.,  1.,  1., 15.,  8.,  3.,  3.,
       13.,  5., 10., 12., 13.,  5.,  4.,  6.,  9.,  8.,  7.,  5., 10.,
       19., 22., 19., 27.,  4.,  5.,  4.,  3., 20., 15., 20., 22., 35.,
        7.,  5.,  7.,  2.,  5.,  2.,  6.,  7.,  4., 23., 35.,  1.,  9.,
        5.,  4.,  6., 20.,  1.,  8.,  6., 11.,  3.,  0.,  0.,  0.,  0.,
        7.,  8., 26., 21., 21., 26., 42., 62., 79., 12., 12.,  8.,  4.,
        7.,  5.,  9.,  8., 55., 51.,  7., 12.,  6., 10., 48., 29., 16.,
       25., 36., 41., 30., 38., 56., 65.,  3.,  1.,  4., 10.,  1.,  3.,
        9.,  7.,  9.,  6.,  8., 44., 33.,  8.,  9.,  1.,  0., 20., 19.,
       22., 29.,  6.,  5.,  3., 13.,  8.,  5.,  7., 27., 26., 27.,  5.,
        5.,  6.,  5.,  5.,  8.,  4.,  7.,  5.,  9., 24., 25.,  4.,  4.,
        6.,  7., 15.,  7., 11., 10.,  8., 16., 22., 23., 31.,  5.,  2.,
        7.,  3., 15., 17., 19.,  3.,  1.,  5.,  6.,  2.,  3.,  8.,  8.,
        2.,  9., 18., 13., 11., 17., 15.,  5.,  3.,  4.,  2.,  9., 10.,
        4.,  2.,  1.,  7.,  1.,  2.,  3.,  4.,  9.,  2.,  6., 18., 18.,
       17.,  9., 15., 17., 10., 22., 26., 33.,  6.,  3.,  3.,  4.,  7.,
        1., 16., 10.,  6.,  6.,  8.,  3.,  2.,  4.,  5.,  2., 20.,  8.,
        0.,  0.,  0.,  0., 14., 15.,  3.,  1.,  2.,  1.,  2.,  5.,  3.,
        3.,  6.,  4., 11., 11., 16., 13.,  2.,  9.,  5., 14., 20.,  4.,
        3.,  3.,  4., 10.,  6., 28., 17., 32.,  3.,  8.,  6.,  8., 13.,
       18.,  9.,  1.,  8.,  7., 17., 22., 20., 20.,  5.,  3.,  0.,  4.,
        7.,  5.,  3.,  7.,  2.,  4.,  4.,  6., 37.,  7.,  5.,  7.,  2.,
        4., 12.,  2.,  2., 26., 36., 34., 27., 25., 36., 69., 88.,  5.,
        4., 35., 17., 18., 26., 30., 49.,  2.,  4.,  2.,  5., 15., 17.,
       30., 11.,  6.,  3., 10., 15.,  5.])

In [29]:
diff_reviews = df['reviews'].diff().values
diff_reviews

array([nan,  1.,  2.,  2.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  2.,  2.,
        2.,  2.,  1.,  2.,  0.,  4.,  1.,  1.,  1.,  2.,  2.,  0.,  3.,
        2.,  0.,  2.,  1.,  2.,  0.,  0.,  0.,  3.,  2.,  0.,  2.,  0.,
        0.,  2.,  0.,  0.,  1.,  1.,  1.,  3.,  3.,  2.,  1.,  1.,  2.,
        0.,  3.,  0.,  1.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  2.,  1.,
        2.,  0.,  3.,  0.,  0.,  1.,  0.,  3.,  0.,  2.,  2.,  0.,  0.,
        2.,  3.,  2.,  0.,  2.,  2.,  2.,  0.,  0.,  2.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  2.,  1.,  0.,  1.,  0.,  1.,  0.,  3.,  1.,
        1.,  1.,  3.,  3.,  5.,  2.,  3.,  1.,  2.,  2.,  2.,  1.,  3.,
        2.,  4.,  5.,  0.,  2.,  0.,  3.,  0.,  5.,  0.,  2.,  0.,  3.,
        4.,  5.,  1.,  1.,  0.,  3.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,
        4.,  1.,  2.,  2.,  3.,  2.,  5.,  1.,  4.,  3.,  5.,  2.,  1.,
        1.,  1.,  0.,  0.,  6.,  3.,  4.,  0.,  6.,  2.,  2.,  5.,  1.,
        0.,  2.,  0.,  6.,  0.,  4.,  1.,  0.,  2.,  0.,  2.,  3.,  0.,
        7.,  0.,  3.,  1.,  5.,  1.,  1.,  2.,  4.,  4.,  3.,  6.,  3.,
        2.,  1.,  1.,  2.,  0.,  4.,  2.,  0.,  1.,  0.,  1.,  1.,  2.,
        1.,  3.,  0.,  2.,  1.,  1.,  3.,  1.,  3.,  1.,  0.,  3.,  2.,
        3.,  4.,  3.,  2.,  0.,  5.,  1.,  1.,  1.,  1.,  2.,  0.,  1.,
        0.,  1.,  2.,  2.,  0.,  1.,  3.,  0.,  3.,  0.,  2.,  4.,  5.,
        0.,  2.,  2.,  0.,  4.,  0.,  3.,  1.,  1.,  1.,  2.,  1.,  2.,
        2.,  2.,  4.,  2.,  3.,  4.,  2.,  2.,  3.,  2.,  3.,  2.,  0.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  4.,  0.,  1.,  1.,  1.,  4.,
        1.,  0.,  3.,  0.,  2.,  0.,  3.,  2.,  2.,  1.,  3.,  0.,  1.,
        1.,  2.,  0.,  1.,  0.,  3.,  2.,  0.,  3.,  0.,  0.,  4.,  5.,
        5.,  0.,  1.,  1.,  2.,  2.,  3.,  0.,  0.,  3.,  2.,  0.,  4.,
        0.,  3.,  0.,  2.,  2.,  0.,  1.,  2.,  2.,  1.,  0.,  1.,  0.,
        0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  2.,  1.,  7.,  4.,  4.,
        0.,  3.,  1.,  4.,  2.,  2.,  1.,  1.,  2.,  0.,  4.,  4.,  1.,
        0.,  2.,  2.,  4.,  2.,  3.,  2.,  0.,  3.,  0.,  0.,  1.,  0.,
        1.,  3.,  4.,  0.,  0.,  1.,  3.,  3.,  2.,  4.,  1.,  2.,  7.,
        2.,  3.,  4.,  2.,  0.,  3.,  3.,  1.,  0.,  1.,  0.,  5.,  1.,
        1.,  2.,  1.,  1.,  3.,  0.,  2.,  7.,  5.,  3.,  1.,  0.,  3.,
        0.,  5.,  4.,  3.,  0.,  2.,  5.,  4.,  2.,  4.,  2.,  5.,  1.,
        5.,  4.,  5.,  2.,  1.,  1.,  1.,  4.,  1.,  5.,  5.,  6.,  3.,
        2.,  0.,  3.,  5.,  4.,  2.,  2.,  1.,  2.,  0.,  0.,  0.,  0.,
        4.,  4.,  1.,  0.,  5.,  4.,  1.,  4.,  7.,  3.,  2., 12.,  3.,
        5.,  2.,  4.,  4.,  1.,  5.,  4.,  3.,  4.,  8.,  6., 11.,  8.,
        7.,  6.,  3., 18.,  7.,  2.,  5.,  6.,  5.,  7.,  1.,  7.,  2.,
        2.,  4.,  5.,  5.,  3.,  4.,  2.,  2.,  3.,  1.,  2.,  4.,  3.,
        0.,  9.,  2.,  1.,  5.,  4.,  5.,  5.,  4.,  1.,  4.,  7.,  4.,
        3.,  1.,  2.,  3.,  2.,  4.,  3.,  3.,  4.,  1.,  2.,  3.,  1.,
        5.,  3.,  3.,  0.,  7.,  1.,  3.,  2.,  3.,  1.,  2.,  2.,  4.,
        2.,  4.,  4.,  0.,  1.,  0.,  4.,  0.,  2.,  4.,  2.,  3.,  2.,
        6.,  4.,  3.,  2.,  2.,  1.,  0.,  2.,  3.,  3.,  1.,  0.,  0.,
        1.,  1.,  3.,  1.,  2.,  5.,  4.,  0.,  0.,  1.,  0.,  3.,  0.,
        2.,  0.,  0.,  3., 10.,  4.,  1.,  1.,  2.,  3.,  1.,  6.,  2.,
        1.,  0.,  0.,  1.,  4.,  2.,  3.,  1.,  2.,  1.,  2.,  1.,  1.,
        0.,  0.,  0.,  0.,  3.,  3.,  2.,  3.,  3.,  2.,  1.,  0.,  0.,
        4.,  2.,  0.,  1.,  3.,  2.,  8.,  1.,  1.,  1.,  1.,  2.,  1.,
        4.,  0.,  2.,  3.,  5.,  4.,  0.,  2.,  4.,  1.,  2.,  3.,  2.,
        2.,  4.,  3.,  0.,  2.,  1.,  1.,  2.,  2.,  4.,  1.,  2.,  0.,
        1.,  2.,  6.,  2.,  3.,  1.,  1.,  1.,  2.,  2.,  4.,  2.,  1.,
        2.,  5.,  0.,  1.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., 23., 17.,  4.,  1., 16.,  4.,  3.,  1.,  3.,  3.,  1.,
        1.,  3.,  4.,  1.,  5.,  1.,  1.])

In [ ]:
df = pd.read_csv('assets/data.csv')

dates = []
for _date in df['date']:
    date = datetime.datetime.strptime(_date,'%Y/%m/%d').date()
    dates.append(date)
    
n_subscribers = df['subscribers'].values
n_reviews = df['reviews'].values

diff_subscribers = df['subscribers'].diff().values
diff_reviews = df['reviews'].diff().values